### ISSUE TITLE
Code Running Error!

### ISSUE THREAD

**Issue by ZSCDumin** [rutgerswiselab/NLR#1]
![image](https://user-images.githubusercontent.com/19670365/98110065-84d1a380-1ed9-11eb-8170-bfa004a89aa2.png)

**Comment by Shuriken13** [comment]
I have modified the main.py and it should be right now.

**Comment by Shuriken13** [comment]
I just clone it on a new device and it runs well.

![image](https://user-images.githubusercontent.com/14871376/98112336-02e37980-1edd-11eb-8d94-baae5e666b3e.png)
