### ISSUE TITLE
有没有pointwise的实现可以参考一下？

### ISSUE THREAD

**Issue by OraserZhang** [rutgerswiselab/NLR#2]

**Comment by Shuriken13** [comment]
原来有个命令行参数 --rank 0表示pointwise评分预测或者点击预测的，不确定现在能不能跑通了。但是模型部分基本都一样呀。

**Comment by OraserZhang** [comment]
还有一个问题，常量true存在的意义是什么呢？没有很明白

**Comment by Shuriken13** [comment]
定标。确定一个参考系吧。如果True的表示不停地变，那怎么让模块能学习到A&True=A或者A|True=True。

**Comment by OraserZhang** [comment]
> 定标。确定一个参考系吧。如果True的表示不停地变，那怎么让模块能学习到A&True=A或者A|True=True。

那true为什么不选择0-1二值，而选择均匀分布呢？

**Comment by Shuriken13** [comment]
你可以改成全0或全1，结果应该是差不多的。
